---

name: rust-audit

on:
  pull_request:
    paths:
      - '**/Cargo.toml'
  push:
    branches:
      - main
      - wip/next
    paths:
      - '**/Cargo.toml'

jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: generate Cargo.lock
        run: cargo generate-lockfile
      - uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

...
